[phases.setup]
nixPkgs = ["nodejs", "chromium", "glibc", "nss", "atk", "cups", "libdrm", "dbus", "libxkbcommon", "mesa", "pango"]

[phases.build]
cmds = ["npm install"]

[variables]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
