[phases.setup]
nixPkgs = ["nodejs", "chromium", "glib", "nss", "nspr", "atk", "at-spi2-atk", "libdrm", "expat", "libxcb", "libxshmfence", "libX11", "libXcomposite", "libXdamage", "libXext", "libXfixes", "libXrandr", "mesa"]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "node index.js"
