[phases.setup]
nixPkgs = ["...", "chromium", "glib", "nss", "atk", "at-spi2-atk", "cups", "libdrm", "libxcb", "libX11", "libXcomposite", "libXdamage", "libXext", "libXfixes", "libXrandr", "mesa", "pango", "cairo", "asound"]
